import GlobalState from '@/context'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Urban Emporium',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar/>
          <main className='flex min-h-screen flex-col mt-[80px]'>{children}</main>
          <footer className="text-white p-4 bg-black">
    <div className="container mx-auto text-center">
        <p>&copy; 2024 Urban Emporium. All rights reserved.</p>
    </div>
</footer>
        </GlobalState>
      </body>
    </html>
  )
}
